### ISSUE TITLE
Swiping instructions are confusing

### ISSUE THREAD

**Issue by echatter** [cs340tabyu/CS340Summer2017#105]
My husband noticed that it says to swipe down for history/chat, and to do so correctly you move your finger down. On the sides, it says to swipe left for player info and to get it you move your finger right, and same on the other side. It's pretty straightforward to figure out, but might be something to fix if you're desperate for things to do.

**Comment by jonandrewj** [comment]
Thanks! We were having a hard time deciding what made sense ourselves... I think we will probably agree that it is inconsistent now! I'm impressed you took the time to read that haha
