### ISSUE TITLE
Double route between San Fancisco and Los Angeles is backwards

### ISSUE THREAD

**Issue by Glowsquirrel** [cs340tabyu/CS340Summer2017#111]
Yellow and purple routes are backwards. Might affect gameplay.
![screenshot_1501915443](https://user-images.githubusercontent.com/25395687/28993578-48522eee-7977-11e7-9f56-0e1a690feb03.png)
![pic3867dfd4](https://user-images.githubusercontent.com/25395687/28993587-68827930-7977-11e7-81a0-a351bc89e548.jpg)

**Comment by shunsambongi** [comment]
I don't really see how this would affect gameplay but I can change the colors if you would like.

**Comment by shunsambongi** [comment]
changed colors
