### ISSUE TITLE
Having enough players doesn't start the game automatically (2 players).

### ISSUE THREAD

**Issue by sonofafinch** [cs340tabyu/CS340Summer2017#15]
Two players are in a two-player game, but the game does not start.
![screenshot_1501866941](https://user-images.githubusercontent.com/14119659/28979263-65019410-7906-11e7-95a2-da3e40f490db.png)

**Comment by sonofafinch** [comment]
This happened to me and Rachael once each, but I have not been able to reproduce it since.

**Comment by Sotaur** [comment]
Unable to reproduce.

**Comment by Sotaur** [comment]
Found by fixing lifecycle issues. Resolved
