### ISSUE TITLE
3 Wild cards in visible deck

### ISSUE THREAD

**Issue by jonandrewj** [cs340tabyu/CS340Summer2017#22]
The deck is re-shuffled after trying to select but the GUI is out of sync until they attempt to select a card.

**Comment by jonandrewj** [comment]
![](https://files.slack.com/files-pri/T60F25X47-F6HRTVAGH/screenshot_20170804-112256.png)

**Comment by jonandrewj** [comment]
![image](https://user-images.githubusercontent.com/29874842/28979618-b747f826-7907-11e7-9f4f-c5c6d2624d66.png)

**Comment by Glowsquirrel** [comment]
This bug was caused by the server sending out the new face up cards out of order. It would send the new card set first, then the old set, resulting in a quick flash of the face up cards, but not changing anything. The server now sends only the correct face up cards.
