### ISSUE TITLE
Card count is out of sync across clients...

### ISSUE THREAD

**Issue by jonandrewj** [cs340tabyu/CS340Summer2017#23]
![image](https://user-images.githubusercontent.com/29874842/28979673-e88dad04-7907-11e7-83da-4a62e6174210.png)

This user has 7 cards but 8 in the display

**Comment by jonandrewj** [comment]
![image](https://user-images.githubusercontent.com/29874842/28979697-032a5374-7908-11e7-8039-17b8dc81cde4.png)

This is another client

**Comment by Glowsquirrel** [comment]
This bug was caused by some inconsistent logic for handling player information. Changes to player information in the top bar has been standardized.
