### ISSUE TITLE
Graphics for the destination cards draw on top of one another so it looks blurry

### ISSUE THREAD

**Issue by Deriboy** [cs340tabyu/CS340Summer2017#33]
also it crashed afterwards.

it happened when we hit the home button and re-entered the app, but we haven't been able to reproduce it in that way so  ¯\\\_(ツ)_/¯

**Comment by sonofafinch** [comment]
Tested this on multiple devices using separate API versions, and I didn't see any issue, aside from a slight shift in text for the number of cards on the available deck cards. There was no change when drawing or in taken cards.
