### ISSUE TITLE
Destination cards are sometimes duplicated.

### ISSUE THREAD

**Issue by sonofafinch** [cs340tabyu/CS340Summer2017#35]
When joining a new game, destination cards are sometimes duplicated. This also happens consistently when re-joining a game, which isn't critical now. Not sure what the common factor is for new games though. Seems random for now.
![screenshot_1501868668](https://user-images.githubusercontent.com/14119659/28980272-71225aa0-790a-11e7-99a3-f79ff349c5ea.png)

**Comment by Sotaur** [comment]
Fixed
