### ISSUE TITLE
The discarded cards are not reshuffled into the deck after it is emptied

### ISSUE THREAD

**Issue by Deriboy** [cs340tabyu/CS340Summer2017#41]

**Comment by sonofafinch** [comment]
![screenshot_1501994130](https://user-images.githubusercontent.com/14119659/29000638-791ae040-7a2e-11e7-87d0-f64c0603b7d5.png)

Currently, it's looking like this is an issue with the server's board model and its shuffle algorithm. Still testing.

**Comment by sonofafinch** [comment]
The issue was caused by a shallow copy of a local variable during shuffling. Should be fixed based on testing. However, the negative values on the client still occur until a person's turn comes around. Looking into that now.

**Comment by sonofafinch** [comment]
Negative values should be fixed.
