### ISSUE TITLE
If a route line is tapped, the route id is displayed in a toast

### ISSUE THREAD

**Issue by greenstack** [cs340tabyu/CS340Summer2017#5]
Clicking a route shows an ambiguous route number - probably a leftover from debugging.

**Comment by jonandrewj** [comment]
![image](https://user-images.githubusercontent.com/29874842/28979790-5dbe874c-7908-11e7-80e3-603191446e2d.png)

**Comment by Glowsquirrel** [comment]
This is a leftover from debugging, and has been fixed.
