### ISSUE TITLE
No click listener on Kansas City to St. Louis

### ISSUE THREAD

**Issue by jonandrewj** [cs340tabyu/CS340Summer2017#50]
I don't think there is a need for a picture here. We were unable to claim with any player in the game.

Los Angeles to Pheonix also appears to not have a listener, same issues

**Comment by jonandrewj** [comment]
It seems like zooming in a lot helped for the Los Angeles to Pheonix route

**Comment by greenstack** [comment]
The same is similar for Kansas City to St. Louis - you need to press around St. Louis, not where the route is.

**Comment by Glowsquirrel** [comment]
Placing objects on a Google map can only be done with markers. Those markers have non-suppressible click listeners that consume the click. This will continue to be an issue as it cannot be resolved with the use of a Google map.
Reference #52 for more details.

**Comment by shunsambongi** [comment]
Changed text to be inside of the city and increased city size to make routes more clickable.
