### ISSUE TITLE
Game get significantly and progressively slower as more actions are performed

### ISSUE THREAD

**Issue by Glowsquirrel** [cs340tabyu/CS340Summer2017#61]
After the game starts, drawing train cards on two different clients runs very quickly (Showing the map again takes ~1s). As they draw more train cards, the client gets significantly slower (Showing the map takes ~3s). After drawing ~30 train cards, showing the map takes ~5s. 
This was done on a lab computer running 2 emulators.

**Comment by Sotaur** [comment]
Probably due to implementation details of RecyclerViews and how updates to them are handled, and the updating of the routes in the map. Closing because not an issue to be fixed at this stage.
