### ISSUE TITLE
Completely different games shown on game list. 

### ISSUE THREAD

**Issue by sjrme** [cs340tabyu/CS340Summer2017#69]
After player a while, logging out, and logging in, the game list on both clients is different. 
![1501874654981-1172094302](https://user-images.githubusercontent.com/30009373/28983760-5f5757cc-7918-11e7-9a0a-e186934dbfa4.jpg)

**Comment by sjrme** [comment]
It doesn' t really require playing awhile, messing around with the back button from the game lobby seems to often produce different lists.

**Comment by Sotaur** [comment]
Fixed poller issues, haven't seen yet

**Comment by Sotaur** [comment]
Fixed, see #20
