### ISSUE TITLE
Turns not working

### ISSUE THREAD

**Issue by echatter** [cs340tabyu/CS340Summer2017#87]
After a player draws a card, they're unable to draw another and the next player can't do anything. This was with a two-player game.

**Comment by Deriboy** [comment]
I have no idea how to reproduce this. This is working fine for me on multiple devices. Can you give us any more detail on this? Same with #86 and #85

**Comment by Deriboy** [comment]
We think you may have pulled an old version of our code somehow. Make sure that you have the most recent version of the master branch please.

**Comment by echatter** [comment]
Our team leader is the one who pulled it, and he just sent us each a copy. I've asked him about it and am waiting to hear back. That would explain a lot, though!

**Comment by echatter** [comment]
Actually, if you get this before he gets my message, could you just give me the link or whatever you gave him? I don't think he's on, and we really need to get working on this. I'll let you know if he answers first.

**Comment by Deriboy** [comment]
https://gitlab.com/jonandrewj/TicketToRide.git

**Comment by echatter** [comment]
This is really weird. I went to your project, made sure the branch dropdown menu thingy said "master," and downloaded a zip file, and it's still acting the same. Is there something you need to do to initialize the game before you can start taking turns?

**Comment by echatter** [comment]
Actually, this is for sure your new one, because the number of pieces is now 45 instead of 10.

**Comment by Deriboy** [comment]
You shouldn't have to do anything besides all players accepting their destination cards. I'm not sure what's going on then. Are your other team members finding the same results?

**Comment by echatter** [comment]
How do you accept your destination cards?

**Comment by Deriboy** [comment]
on the screen with the cards you should see 3 destination cards. you can click on them to toggle them between red and green. green are the ones you keep and red are the ones you discard. when you are done, hit the accept button

**Comment by echatter** [comment]
Where is the accept button?

**Comment by Deriboy** [comment]
can you send me a screenshot of what you see?

**Comment by echatter** [comment]
![card screen](https://user-images.githubusercontent.com/29807823/28991901-af26e400-794c-11e7-8b56-acd82e2f231f.jpg)

**Comment by Deriboy** [comment]
oh, it's off screen. Use an emulator with a larger screen

**Comment by echatter** [comment]
Oh, man. I was so confused! Thanks. Also, it's pretty easy to make the whole screen scrollable. You just wrap everything in a scrollview.

**Comment by Deriboy** [comment]
So can you recheck the couple of issues you made to see if they are still a problem now that you've discovered your problem?

**Comment by echatter** [comment]
Just couldn't see the button to initialize destination cards, which started turns
