### ISSUE TITLE
App is not compatible with small screens

### ISSUE THREAD

**Issue by echatter** [cs340tabyu/CS340Summer2017#89]
When it's running on my phone you can't see the "accept" button to accept your initial destination cards. After the destination cards are accepted (I accepted them on the emulator and then logged in to my phone) they are invisible. The map is completely dominated by the city buttons and you can't see the routes. You could definitely argue that this is a cosmetic issue, but it does halt game play if you're using a phone. My computer can only handle one emulator and I don't have a tablet, so I had to do the initialization for both players on the emulator and then switch to my phone. This issue severely impairs the ability of phone users to strategize because they can't see their maps.
But again, if you're only going to be using this on a tablet it's fine. Which is why I gave it two tags.

**Comment by Ganondox** [comment]
On the phone emulator I ran I didn't have any problems, but on my kindle the city buttons are covering all the routes, so I'm not sure if that's the source of the bug.

**Comment by Deriboy** [comment]
Valid concern, but we're probably not going to fix this at the moment.
