### ISSUE TITLE
Everybody's a winner!

### ISSUE THREAD

**Issue by echatter** [cs340tabyu/CS340Summer2017#91]
This may be a feature, not a bug. I would have lost without it. Here's the screen shots. You can't see it on the phone in the picture, but the same scores are there. They show in a teensy window and you can scroll through one line at a time.
![screenshot_2017-08-04-21-06-42](https://user-images.githubusercontent.com/29807823/28992523-b8c64212-795b-11e7-8f49-5627e0891a4a.png)
![card screen](https://user-images.githubusercontent.com/29807823/28992525-c6c68516-795b-11e7-812a-8df02dae50ef.jpg)

**Comment by echatter** [comment]
Just kidding! On the Elizabfth wins one Elizabfth's final score was 114 and Gail's was 106. Everything else was the same.

**Comment by Deriboy** [comment]
We're not quite sure what is meant here. Are these images from the same game?

**Comment by echatter** [comment]
Yes, those are the two different players in the same game.
The next time we played the game the winners matched on both devices, though. The scores adding up wrong was the only issue then. I'm not sure what we did that caused this to happen. Sorry, we would have tested it more exhaustively, but getting to that screen takes a while.

**Comment by Deriboy** [comment]
Huh that's odd. Thanks for the response. I haven't been able to reproduce that, but i'll look into it some more.
