### ISSUE TITLE
Create games buttons pushed off when enough games are made

### ISSUE THREAD

**Issue by Ganondox** [cs340tabyu/CS340Summer2017#93]

**Comment by Deriboy** [comment]
Can you not scroll down?

**Comment by Ganondox** [comment]
Nope.

**Comment by jonandrewj** [comment]
It's probably a screen being smaller than we tested issue or the fact that we only allow 5 games in the lobby at a time. Either way, we will look into fixing it! Thanks!

**Comment by Deriboy** [comment]
Yeah we made a design decision to limit the number of games you can create to 5 on any given server.
