### ISSUE TITLE
Overlayed Text

### ISSUE THREAD

**Issue by Ganondox** [cs340tabyu/CS340Summer2017#94]
<img width="269" alt="screen shot 2017-08-04 at 9 46 04 pm" src="https://user-images.githubusercontent.com/5442063/28992619-c98aa6ee-795e-11e7-824c-1e596e0295b9.png">

Don't know how I did it aside from scrolling the destination list as I'm struggling to use the interface, might entail a game issue as well, can't tell.

**Comment by Deriboy** [comment]
turn it sideways, that might help
