### ISSUE TITLE
After drawing a number of train cards by both players, drawing cards no longer works, and claiming routes is unsuccessful even if player has sufficient train cards.

### ISSUE THREAD

**Issue by trydalch** [cs340tabyu/CS340Summer2017#95]
In a two player game, I had players repeatedly draw train cards. Eventually, clicking on the face-up train cards became unresponsive, even though it was that player's turn and there were cards in the deck. Attaching screenshots.

![image](https://user-images.githubusercontent.com/17228930/28992660-b8bbce5a-795f-11e7-8521-285336acd1d2.png)

**Comment by Deriboy** [comment]
what did the game history look like? If you're able to reproduce this, could you attach a screenshot of the most recent game history events?

**Comment by trydalch** [comment]
I restarted the app, entered the game, and then was able to continue drawing cards.

As Alexis mentioned, I was unaware that you could not select a wild card as your second card. This may have been the issue, although I believe I attempted to draw several different cards.

**Comment by Ganondox** [comment]
I reproduced this by accident, has nothing to with wild cards.

**Comment by Ganondox** [comment]
Got it to happen somewhat consistently after making many moves in rapid succession, but it sorts itself out on it's own before long so I think it's just a server thing.

**Comment by Ganondox** [comment]
Or might have something to do with the locomotive rules not being enforced properly.
