### ISSUE TITLE
Some train cards are responsive to clicks while others aren't

### ISSUE THREAD

**Issue by trydalch** [cs340tabyu/CS340Summer2017#97]
![image](https://user-images.githubusercontent.com/17228930/28992748-f50494bc-7961-11e7-912c-2b36f4701264.png)

In the game on the left, I drew one face-up train card (the farthest left). This was replaced by the wild-card. When I attempted to draw the wild card as my second card, it was unresponsive. Perhaps this is because it was the card that replaced the one I picked first.

I then attempted to draw the card next to it (it was red), at it was successful. The blue card replaced it.

**Comment by alexis-fisher** [comment]
As per the rules, you can't draw a wild card as your second card. If you attempt to, it will not allow you to do this.

**Comment by trydalch** [comment]
Non-issue then. Thanks for the comment.
